name: Deploy Static Website to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C59802641C3C4334A1C86FB34FEB64DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0502F7D7BBD043D68254854DEF954D67 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0AD82DBC7D1E4FA8AC2AC5077CF91122 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'raushan-ranjan'
          package: .
